version: '3.5'

services:
    
    my-api-web:
        build: ./
        container_name: my-api-web
        networks:
            - my-net
        volumes:
            - ../:/var/www/html/
        ports:
            - "80:80"
    
    my-api-db:
        image: mysql:8.0
        container_name: my-api-db
        networks:
            - my-net
        volumes:
            - ./db/:/var/lib/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: test
            
    my-api-adminer:
        image: adminer
        container_name: my-api-adminer
        networks:
            - my-net
        ports:
            - "8080:8080"
        environment:
            ADMINER_DEFAULT_SERVER: my-api-db
            
networks:
    my-net: